/**
 * The corpus: documents nobody here designed to pass.
 *
 * Every fixture written before this one was authored alongside the feature it
 * exercised, which is how a `.notdef` box in every paragraph survived eight
 * milestones and 156 browser tests. These are written the other way round —
 * the way a customer's document actually looks — and the engine is expected to
 * meet them, not the reverse.
 *
 * Each entry is rendered by `tests/browser/corpus.spec.ts` and held to the same
 * invariants, so adding a document adds coverage without adding assertions.
 */

import { readFileSync } from "node:fs";
import { resolve } from "node:path";

import { checkerboard, fadingDisc, pngDataUrl } from "./png.js";

const FONT_DIR = resolve(import.meta.dirname, "../fonts");

/** A font a corpus document needs, as bytes plus the family it is served as. */
export interface CorpusFont {
  readonly family: string;
  readonly file: string;
  readonly weight?: number;
}

export interface CorpusDocument {
  /** Directory-safe identifier, used for output filenames. */
  readonly name: string;
  /** One line on what this document is for. */
  readonly purpose: string;
  readonly fonts: readonly CorpusFont[];
  /** Markup for the whole page, including the styles it needs. */
  readonly html: string;
  /**
   * How closely extracted text must match what the browser shows.
   *
   * `exact` is the default and the strong form. `unordered` compares the
   * characters without their order, for scripts where a PDF's reading order
   * and the browser's `innerText` legitimately differ — it still catches a
   * dropped or unmapped glyph, which is what the invariant is for.
   *
   * `superset` requires every line the browser shows to appear in the PDF,
   * while allowing the PDF to hold text the source does not: page furniture is
   * generated by `@page` margin boxes and has no counterpart in `innerText`.
   * It still catches anything dropped, which is the point; it cannot catch
   * spurious extra text, so use it only where furniture makes that unavoidable.
   */
  readonly roundTrip?: "exact" | "unordered" | "superset";
  /** Why this document needs the weaker comparison. Required when it does. */
  readonly roundTripNote?: string;
  /**
   * Fewest pages this document must fragment into.
   *
   * Set it where the length is the point. A document meant to break thirty
   * times is worth nothing if a layout change quietly shortens it to two, and
   * nothing else here would notice.
   */
  readonly minPages?: number;
  /**
   * How many image XObjects the PDF must paint.
   *
   * Defaults to none, which is the assertion that matters most here: an image
   * in a document that has none is text that got turned into pixels. Where a
   * document does carry images the exact count is asserted, so a dropped image
   * fails just as loudly as a rasterised paragraph.
   */
  readonly expectedImages?: number;
  /**
   * Pixel widths of every image the PDF embeds, sorted, soft masks included.
   *
   * This is what stops a retina asset being flattened to its display size:
   * a 256px image drawn at 64px must keep 256 pixels or the print is soft,
   * and nothing about the rendered page would reveal the loss.
   */
  readonly imageWidths?: readonly number[];
  /**
   * Strings the PDF must contain that `innerText` never reports.
   *
   * Text inside an `<svg>` is laid out in its own tree, so the round-trip
   * comparison cannot see it: a dashboard whose every axis label vanished
   * would still satisfy `superset`. These are asserted directly.
   */
  readonly mustContain?: readonly string[];
  /**
   * A gap this document is known to expose, as a sentence.
   *
   * The round-trip test is then asserted to *fail*, so that fixing the gap
   * turns CI red and forces this annotation to be removed. A known gap that
   * quietly starts passing is a gap nobody notices has closed.
   */
  readonly knownGap?: string;
}

export function fontBytes(file: string): Uint8Array {
  return new Uint8Array(readFileSync(resolve(FONT_DIR, file)));
}

export function fontDataUrl(file: string): string {
  return `data:font/ttf;base64,${readFileSync(resolve(FONT_DIR, file)).toString("base64")}`;
}

/** `@font-face` rules for a document's fonts. */
function faces(fonts: readonly CorpusFont[]): string {
  return fonts
    .map(
      (font) => `
  @font-face {
    font-family: "${font.family}";
    src: url("${fontDataUrl(font.file)}") format("truetype");
    font-weight: ${font.weight ?? 400};
    font-style: normal;
  }`,
    )
    .join("\n");
}

/** Wrap a body in a page whose subject is sized to a printable column. */
function page(options: {
  readonly fonts: readonly CorpusFont[];
  readonly css: string;
  readonly body: string;
  readonly dir?: string;
  readonly lang?: string;
}): string {
  return `<!doctype html>
<html${options.lang ? ` lang="${options.lang}"` : ""}${options.dir ? ` dir="${options.dir}"` : ""}>
<head>
<meta charset="utf-8">
<style>${faces(options.fonts)}
  @page { size: A4; margin: 18mm; }
  html, body { margin: 0; padding: 0; background: rgb(255, 255, 255); }
  #subject { width: 174mm; background: rgb(255, 255, 255); }
${options.css}
</style>
</head>
<body>
  <div id="subject"${options.dir ? ` dir="${options.dir}"` : ""}>
${options.body}
  </div>
</body>
</html>`;
}

const MONO: CorpusFont = { family: "Corpus Mono", file: "DejaVuSansMono.ttf" };
const ARABIC: CorpusFont = { family: "Corpus Arabic", file: "NotoSansArabic.ttf" };
const HEBREW: CorpusFont = { family: "Corpus Hebrew", file: "NotoSansHebrew.ttf" };
const JAPANESE: CorpusFont = { family: "Corpus JP", file: "NotoSansJP-subset.ttf" };
/** Proportional, and paired with a real bold face rather than a synthesised one. */
const SERIF: CorpusFont = { family: "Corpus Serif", file: "DejaVuSerif.ttf" };
const SERIF_BOLD: CorpusFont = {
  family: "Corpus Serif",
  file: "DejaVuSerif-Bold.ttf",
  weight: 700,
};

/**
 * An invoice built from utility classes.
 *
 * Shaped like what a CSS framework emits: flex rows, a grid, small padded
 * badges, borders on individual sides. Not a hand-tuned document flow.
 */
const invoice: CorpusDocument = {
  name: "invoice",
  purpose: "utility-class CSS, flexbox and grid, the way a framework emits it",
  fonts: [MONO],
  html: page({
    fonts: [MONO],
    css: `
  #subject { font-family: "Corpus Mono", monospace; font-size: 10pt; color: rgb(24,24,27); }
  .flex { display: flex; }
  .between { justify-content: space-between; }
  .items-start { align-items: flex-start; }
  .col { flex-direction: column; }
  .gap-2 { gap: 8px; }
  .gap-6 { gap: 24px; }
  .grid-3 { display: grid; grid-template-columns: repeat(3, minmax(0, 1fr)); gap: 16px; }
  .p-4 { padding: 16px; }
  .mb-6 { margin-bottom: 24px; }
  .rounded { border-radius: 6px; }
  .border { border: 1px solid rgb(228,228,231); }
  .bg-muted { background: rgb(250,250,251); }
  .badge { display: inline-block; padding: 2px 8px; border-radius: 999px;
           background: rgb(219,234,254); color: rgb(30,64,175); font-size: 8pt; }
  .right { text-align: right; }
  .muted { color: rgb(113,113,122); }
  .h1 { font-size: 20pt; font-weight: bold; margin: 0 0 4px; }
  table { width: 100%; border-collapse: collapse; margin: 16px 0; }
  th, td { padding: 6px 8px; border-bottom: 1px solid rgb(228,228,231); font-size: 9pt; }
  th { text-align: left; background: rgb(244,244,245); }`,
    body: `    <div class="flex between items-start mb-6">
      <div>
        <p class="h1">Invoice</p>
        <p class="muted" style="margin:0">INV-2026-0417</p>
        <p style="margin:8px 0 0"><span class="badge">Paid</span></p>
      </div>
      <div class="right muted">
        <p style="margin:0">Northwind Analytics Ltd</p>
        <p style="margin:0">14 Rookery Lane</p>
        <p style="margin:0">Bristol BS1 4TR</p>
      </div>
    </div>

    <div class="grid-3 mb-6">
      <div class="border rounded p-4 bg-muted">
        <p class="muted" style="margin:0 0 4px">Issued</p>
        <p style="margin:0">14 March 2026</p>
      </div>
      <div class="border rounded p-4 bg-muted">
        <p class="muted" style="margin:0 0 4px">Due</p>
        <p style="margin:0">13 April 2026</p>
      </div>
      <div class="border rounded p-4 bg-muted">
        <p class="muted" style="margin:0 0 4px">Total</p>
        <p style="margin:0">GBP 18,420.00</p>
      </div>
    </div>

    <table>
      <thead>
        <tr><th>Description</th><th>Qty</th><th>Unit</th><th>Amount</th></tr>
      </thead>
      <tbody>
        <tr><td>Platform licence, annual</td><td>1</td><td>12,000.00</td><td>12,000.00</td></tr>
        <tr><td>Additional seats</td><td>14</td><td>240.00</td><td>3,360.00</td></tr>
        <tr><td>Onboarding and migration</td><td>1</td><td>2,400.00</td><td>2,400.00</td></tr>
        <tr><td>Priority support</td><td>1</td><td>660.00</td><td>660.00</td></tr>
      </tbody>
    </table>

    <div class="flex col gap-2" style="align-items: flex-end">
      <p style="margin:0" class="muted">Subtotal 18,420.00</p>
      <p style="margin:0" class="muted">VAT (0%) 0.00</p>
      <p style="margin:0"><strong>Total due GBP 18,420.00</strong></p>
    </div>`,
  }),
};

/** Nested tables with spans, which report generators produce constantly. */
const tables: CorpusDocument = {
  name: "tables",
  purpose: "colspan, rowspan and a nested table inside a cell",
  fonts: [MONO],
  html: page({
    fonts: [MONO],
    css: `
  #subject { font-family: "Corpus Mono", monospace; font-size: 9pt; color: rgb(24,24,27); }
  table { width: 100%; border-collapse: collapse; margin-bottom: 16px; }
  th, td { border: 1px solid rgb(200,200,206); padding: 5px 7px; vertical-align: top; }
  th { background: rgb(240,242,248); }
  table table { margin: 0; font-size: 8pt; }`,
    body: `    <h2>Consolidated position</h2>
    <table>
      <thead>
        <tr>
          <th rowspan="2">Entity</th>
          <th colspan="3">Quarter</th>
          <th rowspan="2">Total</th>
        </tr>
        <tr><th>Q1</th><th>Q2</th><th>Q3</th></tr>
      </thead>
      <tbody>
        <tr><td>Northwind UK</td><td>1,200</td><td>1,340</td><td>1,510</td><td>4,050</td></tr>
        <tr>
          <td>Northwind EU</td>
          <td colspan="3">
            Restated — see the breakdown
            <table>
              <tr><th>Region</th><th>Value</th></tr>
              <tr><td>DACH</td><td>820</td></tr>
              <tr><td>Benelux</td><td>410</td></tr>
              <tr><td>Nordics</td><td>385</td></tr>
            </table>
          </td>
          <td>1,615</td>
        </tr>
        <tr><td>Northwind US</td><td>2,050</td><td>2,240</td><td>2,600</td><td>6,890</td></tr>
      </tbody>
    </table>`,
  }),
};

/** Right-to-left Hebrew, which needs bidi but no contextual shaping. */
const hebrew: CorpusDocument = {
  name: "rtl-hebrew",
  purpose: "right-to-left flow and bidi, without contextual shaping",
  fonts: [HEBREW, MONO],
  // Renders correctly — verified by eye against the browser's own painting.
  // pdf.js reports right-to-left runs in a different order from `innerText`,
  // so the ordered comparison fails on the extractor's behaviour rather than
  // the renderer's. Characters are still compared, so a lost glyph is caught.
  roundTrip: "unordered",
  roundTripNote: "pdf.js orders right-to-left runs differently from innerText",
  html: page({
    fonts: [HEBREW, MONO],
    dir: "rtl",
    lang: "he",
    css: `
  #subject { font-family: "Corpus Hebrew", "Corpus Mono", sans-serif; font-size: 12pt;
             color: rgb(24,24,27); line-height: 1.7; }
  h2 { font-size: 15pt; margin: 0 0 8px; }
  p { margin: 0 0 10px; }`,
    body: `    <h2>דוח רבעוני</h2>
    <p>ההכנסות גדלו בארבעה עשר אחוזים ברבעון הנוכחי לעומת הרבעון הקודם.</p>
    <p>שולי הרווח השתפרו בשני האזורים הראשונים שעברו למערכת החדשה.</p>
    <p>סך הכל נרשמו 4,182 חשבונות פעילים בסוף התקופה.</p>`,
  }),
};

/**
 * Right-to-left Arabic, which needs contextual shaping.
 *
 * Arabic letters change form by position in the word, and a browser applies
 * the font's GSUB tables to choose them. Anything that maps characters to
 * glyphs through `cmap` alone gets the isolated form every time, and the text
 * renders as disconnected letters.
 */
const arabic: CorpusDocument = {
  name: "rtl-arabic",
  purpose: "contextual shaping — the case a cmap-only glyph lookup cannot serve",
  fonts: [ARABIC, MONO],
  knownGap:
    "No text shaping. Glyphs are looked up through the font's cmap alone, so " +
    "every Arabic letter gets its isolated form and the words render as " +
    "disconnected letters at wrong positions. Fixing this needs GSUB/GPOS " +
    "application, not a patch.",
  html: page({
    fonts: [ARABIC, MONO],
    dir: "rtl",
    lang: "ar",
    css: `
  #subject { font-family: "Corpus Arabic", "Corpus Mono", sans-serif; font-size: 13pt;
             color: rgb(24,24,27); line-height: 1.8; }
  h2 { font-size: 16pt; margin: 0 0 8px; }
  p { margin: 0 0 10px; }`,
    body: `    <h2>التقرير الربعي</h2>
    <p>ارتفعت الإيرادات بنسبة أربعة عشر بالمئة مقارنة بالربع السابق.</p>
    <p>تحسنت هوامش الربح في المنطقتين اللتين انتقلتا أولا إلى النظام الجديد.</p>`,
  }),
};

/** Japanese, which wraps between characters rather than at spaces. */
const japanese: CorpusDocument = {
  name: "cjk-japanese",
  purpose: "CJK line breaking, which happens between characters and not at spaces",
  fonts: [JAPANESE, MONO],
  html: page({
    fonts: [JAPANESE, MONO],
    lang: "ja",
    css: `
  #subject { font-family: "Corpus JP", "Corpus Mono", sans-serif; font-size: 12pt;
             color: rgb(24,24,27); line-height: 1.9; }
  h2 { font-size: 15pt; margin: 0 0 8px; }
  p { margin: 0 0 10px; }
  table { border-collapse: collapse; width: 100%; }
  td, th { border: 1px solid rgb(200,200,206); padding: 5px 8px; }`,
    body: `    <h2>四半期業績報告書</h2>
    <p>東京支店の売上高は前年同期比で増加した。営業利益も同様に改善している。</p>
    <p>顧客数の合計は本書の表に示す。注記は日本語版のみとする。</p>
    <table>
      <tr><th>支店</th><th>売上高</th><th>顧客数</th></tr>
      <tr><td>東京</td><td>1,510</td><td>282</td></tr>
      <tr><td>大阪</td><td>1,240</td><td>197</td></tr>
    </table>`,
  }),
};

/**
 * Sentences to build long-form prose from.
 *
 * Fixed, never generated, so the document is byte-identical between runs — the
 * determinism invariant is worthless if the input drifts. They vary in length
 * on purpose: equal-length paragraphs would land every page break in the same
 * relative position and exercise one case thirty times over.
 */
const PROSE: readonly string[] = [
  "Revenue for the period rose against a comparable quarter, with the largest single contribution coming from renewals rather than new business.",
  "Margin improved by a smaller amount than volume, which is the pattern the previous two reports described and the finance committee has asked to see sustained.",
  "The northern region completed its migration first and has been the cleanest source of comparable figures since.",
  "Headcount was flat.",
  "Costs associated with the transition are presented separately below, on the basis that treating them as ordinary operating expense would obscure the underlying trend for anyone reading the series year on year.",
  "Two contracts were renegotiated during the period; neither materially changes the recognised amount, and both extend the term.",
  "The committee reviewed the assumptions behind the forecast and left them unchanged.",
  "Working capital moved in line with the seasonal pattern, and the small variance against plan is attributable to the timing of a single supplier payment that fell either side of the period end depending on the treatment applied.",
];

/**
 * A long-form report: proportional type, real weights, and thirty-odd pages.
 *
 * Every other document in the corpus is monospace and fits on a page or two,
 * which hides two whole classes of problem: proportional metrics and kerning,
 * and everything that only happens once content is fragmented many times over
 * — running headers that must track the current chapter, page counters that
 * are only correct after a second pass, and orphans and widows at thirty
 * separate breaks rather than one.
 */
const report: CorpusDocument = {
  name: "long-report",
  purpose: "thirty-odd pages of proportional type, running headers and page counters",
  fonts: [SERIF, SERIF_BOLD],
  roundTrip: "superset",
  minPages: 30,
  roundTripNote:
    "Margin boxes add page numbers and a running header, which have no counterpart in innerText.",
  html: page({
    fonts: [SERIF, SERIF_BOLD],
    css: `
  @page {
    @top-right { content: string(chapter); font-family: "Corpus Serif", serif;
                 font-size: 8pt; color: rgb(113,113,122); }
    @bottom-center { content: "Page " counter(page) " of " counter(pages);
                     font-family: "Corpus Serif", serif; font-size: 8pt;
                     color: rgb(113,113,122); }
  }
  #subject { font-family: "Corpus Serif", serif; font-size: 11pt; line-height: 1.55;
             color: rgb(24,24,27); orphans: 2; widows: 2; }
  h1 { font-size: 20pt; font-weight: bold; margin: 0 0 16px; }
  h2 { font-size: 14pt; font-weight: bold; margin: 24px 0 8px;
       string-set: chapter content(); break-after: avoid; }
  p { margin: 0 0 11px; text-align: justify; }`,
    body: [
      `    <h1>Annual Review</h1>`,
      ...Array.from({ length: 24 }, (_unused, chapter) => {
        const heading = `    <h2>Section ${chapter + 1}</h2>`;
        // Eight paragraphs a section, each a different rotation through the
        // sentence pool, so no two paragraphs are the same length.
        const paragraphs = Array.from({ length: 8 }, (_ignored, index) => {
          const start = (chapter * 8 + index) % PROSE.length;
          const sentences = Array.from(
            { length: 3 + ((chapter + index) % 3) },
            (_each, offset) => PROSE[(start + offset) % PROSE.length] as string,
          );
          return `    <p>${sentences.join(" ")}</p>`;
        });
        return [heading, ...paragraphs].join("\n");
      }),
    ].join("\n"),
  }),
};

/**
 * Images: several densities, and one with an alpha channel.
 *
 * The density cases are the ones that matter for a print target. An image
 * drawn smaller than its pixels is what a retina asset does, and the PDF must
 * keep the pixels rather than the display size or the print is soft. An image
 * drawn larger is the opposite mistake and must not be silently upsampled.
 *
 * The transparent one sits on a coloured panel, so a soft mask that is ignored
 * or inverted is obvious rather than subtle.
 */
const images: CorpusDocument = {
  name: "images",
  purpose: "raster images at three densities, one of them with transparency",
  fonts: [MONO],
  expectedImages: 4,
  // Three checkerboards at their source sizes, and the disc twice over: once
  // as colour and once as the soft mask carrying its alpha.
  imageWidths: [16, 64, 96, 96, 256],
  html: page({
    fonts: [MONO],
    css: `
  #subject { font-family: "Corpus Mono", monospace; font-size: 10pt; color: rgb(24,24,27); }
  h2 { font-size: 13pt; margin: 0 0 12px; }
  figure { margin: 0 0 18px; }
  figcaption { font-size: 8pt; color: rgb(113,113,122); margin-top: 4px; }
  .panel { background: rgb(30,64,175); padding: 12px; display: inline-block; }
  .row { display: flex; gap: 16px; align-items: flex-start; }`,
    body: `    <h2>Image density</h2>
    <div class="row">
      <figure>
        <img src="${pngDataUrl(64, 64, checkerboard(8, [244, 244, 245], [24, 24, 27]))}"
             width="64" height="64" alt="64px checkerboard at its own size">
        <figcaption>64px source, drawn at 64px</figcaption>
      </figure>
      <figure>
        <img src="${pngDataUrl(256, 256, checkerboard(32, [219, 234, 254], [30, 64, 175]))}"
             width="64" height="64" alt="256px checkerboard drawn small">
        <figcaption>256px source, drawn at 64px</figcaption>
      </figure>
      <figure>
        <img src="${pngDataUrl(16, 16, checkerboard(2, [254, 226, 226], [153, 27, 27]))}"
             width="64" height="64" alt="16px checkerboard drawn large">
        <figcaption>16px source, drawn at 64px</figcaption>
      </figure>
    </div>

    <h2>Transparency</h2>
    <figure>
      <span class="panel">
        <img src="${pngDataUrl(96, 96, fadingDisc(96, [255, 255, 255]))}"
             width="96" height="96" alt="White disc fading to transparent">
      </span>
      <figcaption>Alpha channel over a solid panel</figcaption>
    </figure>`,
  }),
};


/**
 * A dashboard: three charts on one page, with legends and axis labels.
 *
 * The brief names this as a target use case, and it is the document that
 * exercises SVG and text together — a chart is worthless in print if the
 * numbers beside it are missing, and until labels rendered this page would
 * have come out as unannotated shapes.
 */
const dashboard: CorpusDocument = {
  name: "dashboard",
  purpose: "several charts on one page, with legends and axis labels",
  fonts: [MONO],
  roundTrip: "superset",
  roundTripNote:
    "Text inside SVG is laid out in its own tree, which innerText does not report.",
  // Every label on every chart, since the round-trip comparison is blind to
  // them. One from each axis, each legend and each series.
  mustContain: [
    "20",
    "Q1",
    "Q4",
    "GBP m",
    "2024",
    "2026",
    "Enterprise",
    "Self-serve",
    "North",
    "Export",
    "1,204 tickets",
    "742 tickets",
    "Twelve months to March 2026",
  ],
  html: page({
    fonts: [MONO],
    css: `
  #subject { font-family: "Corpus Mono", monospace; font-size: 10pt; color: rgb(24,24,27); }
  h1 { font-size: 16pt; margin: 0 0 4px; }
  .sub { color: rgb(113,113,122); font-size: 9pt; margin: 0 0 16px; }
  .grid { display: grid; grid-template-columns: 1fr 1fr; gap: 16px; }
  .card { border: 1px solid rgb(228,228,231); border-radius: 6px; padding: 12px; }
  .card h2 { font-size: 11pt; margin: 0 0 8px; }
  .wide { grid-column: 1 / -1; }
  svg { display: block; font-family: "Corpus Mono", monospace; }
  .axis { font-size: 7px; fill: rgb(113,113,122); }
  .key { font-size: 7px; fill: rgb(24,24,27); }`,
    body: `    <h1>Operations dashboard</h1>
    <p class="sub">Rolling twelve months to March 2026</p>

    <div class="grid">
      <div class="card">
        <h2>Revenue by quarter</h2>
        <svg width="286" height="143" viewBox="0 0 200 100">
          <line x1="24" y1="8" x2="24" y2="78" stroke="rgb(212,212,216)" stroke-width="0.7"/>
          <line x1="24" y1="78" x2="192" y2="78" stroke="rgb(212,212,216)" stroke-width="0.7"/>

          <rect x="36" y="46" width="24" height="32" fill="rgb(30,64,175)"/>
          <rect x="76" y="34" width="24" height="44" fill="rgb(30,64,175)"/>
          <rect x="116" y="52" width="24" height="26" fill="rgb(30,64,175)"/>
          <rect x="156" y="22" width="24" height="56" fill="rgb(30,64,175)"/>

          <text class="axis" x="20" y="11" text-anchor="end">20</text>
          <text class="axis" x="20" y="45" text-anchor="end">10</text>
          <text class="axis" x="20" y="80" text-anchor="end">0</text>

          <text class="axis" x="48" y="88" text-anchor="middle">Q1</text>
          <text class="axis" x="88" y="88" text-anchor="middle">Q2</text>
          <text class="axis" x="128" y="88" text-anchor="middle">Q3</text>
          <text class="axis" x="168" y="88" text-anchor="middle">Q4</text>
          <text class="axis" transform="translate(8,43) rotate(-90)"
                text-anchor="middle">GBP m</text>
        </svg>
      </div>

      <div class="card">
        <h2>Retention</h2>
        <svg width="286" height="143" viewBox="0 0 200 100">
          <polyline points="30,66 66,54 102,58 138,38 174,26" fill="none"
                    stroke="rgb(30,64,175)" stroke-width="2"
                    stroke-linecap="round" stroke-linejoin="round"/>
          <polyline points="30,72 66,70 102,66 138,64 174,60" fill="none"
                    stroke="rgb(153,27,27)" stroke-width="1.5"
                    stroke-dasharray="4 3"/>

          <circle cx="174" cy="26" r="2.5" fill="rgb(30,64,175)"/>

          <text class="axis" x="30" y="88">2024</text>
          <text class="axis" x="174" y="88" text-anchor="end">2026</text>

          <rect x="112" y="6" width="6" height="3" fill="rgb(30,64,175)"/>
          <text class="key" x="122" y="9">Enterprise</text>
          <rect x="112" y="14" width="6" height="3" fill="rgb(153,27,27)"/>
          <text class="key" x="122" y="17">Self-serve</text>
        </svg>
      </div>

      <div class="card wide">
        <h2>Support load by region</h2>
        <svg width="600" height="129" viewBox="0 0 400 86">
          <line x1="60" y1="70" x2="392" y2="70" stroke="rgb(212,212,216)" stroke-width="0.7"/>

          <rect x="60" y="14" width="86" height="12" fill="rgb(30,64,175)"/>
          <rect x="60" y="32" width="132" height="12" fill="rgb(37,99,235)"/>
          <rect x="60" y="50" width="58" height="12" fill="rgb(147,197,253)"/>

          <text class="axis" x="56" y="23" text-anchor="end">North</text>
          <text class="axis" x="56" y="41" text-anchor="end">South</text>
          <text class="axis" x="56" y="59" text-anchor="end">Export</text>

          <text class="key" x="152" y="23">1,204 tickets</text>
          <text class="key" x="198" y="41">1,878 tickets</text>
          <text class="key" x="124" y="59">742 tickets</text>

          <text class="axis" x="226" y="82" text-anchor="middle">Twelve months to March 2026</text>
        </svg>
      </div>
    </div>`,
  }),
};

export const CORPUS: readonly CorpusDocument[] = [
  invoice,
  tables,
  hebrew,
  arabic,
  japanese,
  report,
  images,
  dashboard,
];
